version: '1'
services: 
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgress_password
    api:
        depends_on: 
            - postgres
        restart: always
        image:
            ports:
                - "3000:3000"
            volumes: 
                - /app/nodes_modules
                - .:/app
        environment: 
            - POSTGRES_USERNAME=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgress_password
            - POSTGRES_PORT=5432